/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CToken } from "./CToken";
export type { CompoundOracle } from "./CompoundOracle";
export type { Comptroller } from "./Comptroller";
export type { MorphoCompound } from "./MorphoCompound";
export type { MorphoCompoundLens } from "./MorphoCompoundLens";
export type { MorphoCompoundSupplyVault } from "./MorphoCompoundSupplyVault";
