/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface LendingPoolConfiguratorInterface extends utils.Interface {
  functions: {
    "activateReserve(address)": FunctionFragment;
    "configureReserveAsCollateral(address,uint256,uint256,uint256)": FunctionFragment;
    "deactivateReserve(address)": FunctionFragment;
    "disableBorrowingOnReserve(address)": FunctionFragment;
    "disableReserveStableRate(address)": FunctionFragment;
    "enableBorrowingOnReserve(address,bool)": FunctionFragment;
    "enableReserveStableRate(address)": FunctionFragment;
    "freezeReserve(address)": FunctionFragment;
    "initReserve(address,address,address,uint8,address)": FunctionFragment;
    "initialize(address)": FunctionFragment;
    "setPoolPause(bool)": FunctionFragment;
    "setReserveFactor(address,uint256)": FunctionFragment;
    "setReserveInterestRateStrategyAddress(address,address)": FunctionFragment;
    "unfreezeReserve(address)": FunctionFragment;
    "updateAToken(address,address)": FunctionFragment;
    "updateStableDebtToken(address,address)": FunctionFragment;
    "updateVariableDebtToken(address,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "activateReserve"
      | "configureReserveAsCollateral"
      | "deactivateReserve"
      | "disableBorrowingOnReserve"
      | "disableReserveStableRate"
      | "enableBorrowingOnReserve"
      | "enableReserveStableRate"
      | "freezeReserve"
      | "initReserve"
      | "initialize"
      | "setPoolPause"
      | "setReserveFactor"
      | "setReserveInterestRateStrategyAddress"
      | "unfreezeReserve"
      | "updateAToken"
      | "updateStableDebtToken"
      | "updateVariableDebtToken"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "activateReserve",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "configureReserveAsCollateral",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateReserve",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "disableBorrowingOnReserve",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "disableReserveStableRate",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "enableBorrowingOnReserve",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "enableReserveStableRate",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "freezeReserve",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "initReserve",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setPoolPause",
    values: [PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "setReserveFactor",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setReserveInterestRateStrategyAddress",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "unfreezeReserve",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAToken",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateStableDebtToken",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateVariableDebtToken",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "activateReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "configureReserveAsCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disableBorrowingOnReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disableReserveStableRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enableBorrowingOnReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enableReserveStableRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "freezeReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPoolPause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReserveFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReserveInterestRateStrategyAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unfreezeReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateStableDebtToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateVariableDebtToken",
    data: BytesLike
  ): Result;

  events: {
    "ATokenUpgraded(address,address,address)": EventFragment;
    "BorrowingDisabledOnReserve(address)": EventFragment;
    "BorrowingEnabledOnReserve(address,bool)": EventFragment;
    "CollateralConfigurationChanged(address,uint256,uint256,uint256)": EventFragment;
    "ReserveActivated(address)": EventFragment;
    "ReserveDeactivated(address)": EventFragment;
    "ReserveDecimalsChanged(address,uint256)": EventFragment;
    "ReserveFactorChanged(address,uint256)": EventFragment;
    "ReserveFrozen(address)": EventFragment;
    "ReserveInitialized(address,address,address,address,address)": EventFragment;
    "ReserveInterestRateStrategyChanged(address,address)": EventFragment;
    "ReserveUnfrozen(address)": EventFragment;
    "StableDebtTokenUpgraded(address,address,address)": EventFragment;
    "StableRateDisabledOnReserve(address)": EventFragment;
    "StableRateEnabledOnReserve(address)": EventFragment;
    "VariableDebtTokenUpgraded(address,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ATokenUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BorrowingDisabledOnReserve"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BorrowingEnabledOnReserve"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "CollateralConfigurationChanged"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReserveActivated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReserveDeactivated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReserveDecimalsChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReserveFactorChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReserveFrozen"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReserveInitialized"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ReserveInterestRateStrategyChanged"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReserveUnfrozen"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StableDebtTokenUpgraded"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "StableRateDisabledOnReserve"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StableRateEnabledOnReserve"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VariableDebtTokenUpgraded"): EventFragment;
}

export interface ATokenUpgradedEventObject {
  asset: string;
  proxy: string;
  implementation: string;
}
export type ATokenUpgradedEvent = TypedEvent<
  [string, string, string],
  ATokenUpgradedEventObject
>;

export type ATokenUpgradedEventFilter = TypedEventFilter<ATokenUpgradedEvent>;

export interface BorrowingDisabledOnReserveEventObject {
  asset: string;
}
export type BorrowingDisabledOnReserveEvent = TypedEvent<
  [string],
  BorrowingDisabledOnReserveEventObject
>;

export type BorrowingDisabledOnReserveEventFilter =
  TypedEventFilter<BorrowingDisabledOnReserveEvent>;

export interface BorrowingEnabledOnReserveEventObject {
  asset: string;
  stableRateEnabled: boolean;
}
export type BorrowingEnabledOnReserveEvent = TypedEvent<
  [string, boolean],
  BorrowingEnabledOnReserveEventObject
>;

export type BorrowingEnabledOnReserveEventFilter =
  TypedEventFilter<BorrowingEnabledOnReserveEvent>;

export interface CollateralConfigurationChangedEventObject {
  asset: string;
  ltv: BigNumber;
  liquidationThreshold: BigNumber;
  liquidationBonus: BigNumber;
}
export type CollateralConfigurationChangedEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  CollateralConfigurationChangedEventObject
>;

export type CollateralConfigurationChangedEventFilter =
  TypedEventFilter<CollateralConfigurationChangedEvent>;

export interface ReserveActivatedEventObject {
  asset: string;
}
export type ReserveActivatedEvent = TypedEvent<
  [string],
  ReserveActivatedEventObject
>;

export type ReserveActivatedEventFilter =
  TypedEventFilter<ReserveActivatedEvent>;

export interface ReserveDeactivatedEventObject {
  asset: string;
}
export type ReserveDeactivatedEvent = TypedEvent<
  [string],
  ReserveDeactivatedEventObject
>;

export type ReserveDeactivatedEventFilter =
  TypedEventFilter<ReserveDeactivatedEvent>;

export interface ReserveDecimalsChangedEventObject {
  asset: string;
  decimals: BigNumber;
}
export type ReserveDecimalsChangedEvent = TypedEvent<
  [string, BigNumber],
  ReserveDecimalsChangedEventObject
>;

export type ReserveDecimalsChangedEventFilter =
  TypedEventFilter<ReserveDecimalsChangedEvent>;

export interface ReserveFactorChangedEventObject {
  asset: string;
  factor: BigNumber;
}
export type ReserveFactorChangedEvent = TypedEvent<
  [string, BigNumber],
  ReserveFactorChangedEventObject
>;

export type ReserveFactorChangedEventFilter =
  TypedEventFilter<ReserveFactorChangedEvent>;

export interface ReserveFrozenEventObject {
  asset: string;
}
export type ReserveFrozenEvent = TypedEvent<[string], ReserveFrozenEventObject>;

export type ReserveFrozenEventFilter = TypedEventFilter<ReserveFrozenEvent>;

export interface ReserveInitializedEventObject {
  asset: string;
  aToken: string;
  stableDebtToken: string;
  variableDebtToken: string;
  interestRateStrategyAddress: string;
}
export type ReserveInitializedEvent = TypedEvent<
  [string, string, string, string, string],
  ReserveInitializedEventObject
>;

export type ReserveInitializedEventFilter =
  TypedEventFilter<ReserveInitializedEvent>;

export interface ReserveInterestRateStrategyChangedEventObject {
  asset: string;
  strategy: string;
}
export type ReserveInterestRateStrategyChangedEvent = TypedEvent<
  [string, string],
  ReserveInterestRateStrategyChangedEventObject
>;

export type ReserveInterestRateStrategyChangedEventFilter =
  TypedEventFilter<ReserveInterestRateStrategyChangedEvent>;

export interface ReserveUnfrozenEventObject {
  asset: string;
}
export type ReserveUnfrozenEvent = TypedEvent<
  [string],
  ReserveUnfrozenEventObject
>;

export type ReserveUnfrozenEventFilter = TypedEventFilter<ReserveUnfrozenEvent>;

export interface StableDebtTokenUpgradedEventObject {
  asset: string;
  proxy: string;
  implementation: string;
}
export type StableDebtTokenUpgradedEvent = TypedEvent<
  [string, string, string],
  StableDebtTokenUpgradedEventObject
>;

export type StableDebtTokenUpgradedEventFilter =
  TypedEventFilter<StableDebtTokenUpgradedEvent>;

export interface StableRateDisabledOnReserveEventObject {
  asset: string;
}
export type StableRateDisabledOnReserveEvent = TypedEvent<
  [string],
  StableRateDisabledOnReserveEventObject
>;

export type StableRateDisabledOnReserveEventFilter =
  TypedEventFilter<StableRateDisabledOnReserveEvent>;

export interface StableRateEnabledOnReserveEventObject {
  asset: string;
}
export type StableRateEnabledOnReserveEvent = TypedEvent<
  [string],
  StableRateEnabledOnReserveEventObject
>;

export type StableRateEnabledOnReserveEventFilter =
  TypedEventFilter<StableRateEnabledOnReserveEvent>;

export interface VariableDebtTokenUpgradedEventObject {
  asset: string;
  proxy: string;
  implementation: string;
}
export type VariableDebtTokenUpgradedEvent = TypedEvent<
  [string, string, string],
  VariableDebtTokenUpgradedEventObject
>;

export type VariableDebtTokenUpgradedEventFilter =
  TypedEventFilter<VariableDebtTokenUpgradedEvent>;

export interface LendingPoolConfigurator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LendingPoolConfiguratorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    activateReserve(
      asset: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    configureReserveAsCollateral(
      asset: PromiseOrValue<string>,
      ltv: PromiseOrValue<BigNumberish>,
      liquidationThreshold: PromiseOrValue<BigNumberish>,
      liquidationBonus: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    deactivateReserve(
      asset: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    disableBorrowingOnReserve(
      asset: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    disableReserveStableRate(
      asset: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    enableBorrowingOnReserve(
      asset: PromiseOrValue<string>,
      stableBorrowRateEnabled: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    enableReserveStableRate(
      asset: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    freezeReserve(
      asset: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    initReserve(
      aTokenImpl: PromiseOrValue<string>,
      stableDebtTokenImpl: PromiseOrValue<string>,
      variableDebtTokenImpl: PromiseOrValue<string>,
      underlyingAssetDecimals: PromiseOrValue<BigNumberish>,
      interestRateStrategyAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    initialize(
      provider: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setPoolPause(
      val: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setReserveFactor(
      asset: PromiseOrValue<string>,
      reserveFactor: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setReserveInterestRateStrategyAddress(
      asset: PromiseOrValue<string>,
      rateStrategyAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unfreezeReserve(
      asset: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateAToken(
      asset: PromiseOrValue<string>,
      implementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateStableDebtToken(
      asset: PromiseOrValue<string>,
      implementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateVariableDebtToken(
      asset: PromiseOrValue<string>,
      implementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  activateReserve(
    asset: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  configureReserveAsCollateral(
    asset: PromiseOrValue<string>,
    ltv: PromiseOrValue<BigNumberish>,
    liquidationThreshold: PromiseOrValue<BigNumberish>,
    liquidationBonus: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  deactivateReserve(
    asset: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  disableBorrowingOnReserve(
    asset: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  disableReserveStableRate(
    asset: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  enableBorrowingOnReserve(
    asset: PromiseOrValue<string>,
    stableBorrowRateEnabled: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  enableReserveStableRate(
    asset: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  freezeReserve(
    asset: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  initReserve(
    aTokenImpl: PromiseOrValue<string>,
    stableDebtTokenImpl: PromiseOrValue<string>,
    variableDebtTokenImpl: PromiseOrValue<string>,
    underlyingAssetDecimals: PromiseOrValue<BigNumberish>,
    interestRateStrategyAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  initialize(
    provider: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setPoolPause(
    val: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setReserveFactor(
    asset: PromiseOrValue<string>,
    reserveFactor: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setReserveInterestRateStrategyAddress(
    asset: PromiseOrValue<string>,
    rateStrategyAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unfreezeReserve(
    asset: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateAToken(
    asset: PromiseOrValue<string>,
    implementation: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateStableDebtToken(
    asset: PromiseOrValue<string>,
    implementation: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateVariableDebtToken(
    asset: PromiseOrValue<string>,
    implementation: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    activateReserve(
      asset: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    configureReserveAsCollateral(
      asset: PromiseOrValue<string>,
      ltv: PromiseOrValue<BigNumberish>,
      liquidationThreshold: PromiseOrValue<BigNumberish>,
      liquidationBonus: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    deactivateReserve(
      asset: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    disableBorrowingOnReserve(
      asset: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    disableReserveStableRate(
      asset: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    enableBorrowingOnReserve(
      asset: PromiseOrValue<string>,
      stableBorrowRateEnabled: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    enableReserveStableRate(
      asset: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    freezeReserve(
      asset: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    initReserve(
      aTokenImpl: PromiseOrValue<string>,
      stableDebtTokenImpl: PromiseOrValue<string>,
      variableDebtTokenImpl: PromiseOrValue<string>,
      underlyingAssetDecimals: PromiseOrValue<BigNumberish>,
      interestRateStrategyAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    initialize(
      provider: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setPoolPause(
      val: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setReserveFactor(
      asset: PromiseOrValue<string>,
      reserveFactor: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setReserveInterestRateStrategyAddress(
      asset: PromiseOrValue<string>,
      rateStrategyAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    unfreezeReserve(
      asset: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateAToken(
      asset: PromiseOrValue<string>,
      implementation: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateStableDebtToken(
      asset: PromiseOrValue<string>,
      implementation: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateVariableDebtToken(
      asset: PromiseOrValue<string>,
      implementation: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ATokenUpgraded(address,address,address)"(
      asset?: PromiseOrValue<string> | null,
      proxy?: PromiseOrValue<string> | null,
      implementation?: PromiseOrValue<string> | null
    ): ATokenUpgradedEventFilter;
    ATokenUpgraded(
      asset?: PromiseOrValue<string> | null,
      proxy?: PromiseOrValue<string> | null,
      implementation?: PromiseOrValue<string> | null
    ): ATokenUpgradedEventFilter;

    "BorrowingDisabledOnReserve(address)"(
      asset?: PromiseOrValue<string> | null
    ): BorrowingDisabledOnReserveEventFilter;
    BorrowingDisabledOnReserve(
      asset?: PromiseOrValue<string> | null
    ): BorrowingDisabledOnReserveEventFilter;

    "BorrowingEnabledOnReserve(address,bool)"(
      asset?: PromiseOrValue<string> | null,
      stableRateEnabled?: null
    ): BorrowingEnabledOnReserveEventFilter;
    BorrowingEnabledOnReserve(
      asset?: PromiseOrValue<string> | null,
      stableRateEnabled?: null
    ): BorrowingEnabledOnReserveEventFilter;

    "CollateralConfigurationChanged(address,uint256,uint256,uint256)"(
      asset?: PromiseOrValue<string> | null,
      ltv?: null,
      liquidationThreshold?: null,
      liquidationBonus?: null
    ): CollateralConfigurationChangedEventFilter;
    CollateralConfigurationChanged(
      asset?: PromiseOrValue<string> | null,
      ltv?: null,
      liquidationThreshold?: null,
      liquidationBonus?: null
    ): CollateralConfigurationChangedEventFilter;

    "ReserveActivated(address)"(
      asset?: PromiseOrValue<string> | null
    ): ReserveActivatedEventFilter;
    ReserveActivated(
      asset?: PromiseOrValue<string> | null
    ): ReserveActivatedEventFilter;

    "ReserveDeactivated(address)"(
      asset?: PromiseOrValue<string> | null
    ): ReserveDeactivatedEventFilter;
    ReserveDeactivated(
      asset?: PromiseOrValue<string> | null
    ): ReserveDeactivatedEventFilter;

    "ReserveDecimalsChanged(address,uint256)"(
      asset?: PromiseOrValue<string> | null,
      decimals?: null
    ): ReserveDecimalsChangedEventFilter;
    ReserveDecimalsChanged(
      asset?: PromiseOrValue<string> | null,
      decimals?: null
    ): ReserveDecimalsChangedEventFilter;

    "ReserveFactorChanged(address,uint256)"(
      asset?: PromiseOrValue<string> | null,
      factor?: null
    ): ReserveFactorChangedEventFilter;
    ReserveFactorChanged(
      asset?: PromiseOrValue<string> | null,
      factor?: null
    ): ReserveFactorChangedEventFilter;

    "ReserveFrozen(address)"(
      asset?: PromiseOrValue<string> | null
    ): ReserveFrozenEventFilter;
    ReserveFrozen(
      asset?: PromiseOrValue<string> | null
    ): ReserveFrozenEventFilter;

    "ReserveInitialized(address,address,address,address,address)"(
      asset?: PromiseOrValue<string> | null,
      aToken?: PromiseOrValue<string> | null,
      stableDebtToken?: null,
      variableDebtToken?: null,
      interestRateStrategyAddress?: null
    ): ReserveInitializedEventFilter;
    ReserveInitialized(
      asset?: PromiseOrValue<string> | null,
      aToken?: PromiseOrValue<string> | null,
      stableDebtToken?: null,
      variableDebtToken?: null,
      interestRateStrategyAddress?: null
    ): ReserveInitializedEventFilter;

    "ReserveInterestRateStrategyChanged(address,address)"(
      asset?: PromiseOrValue<string> | null,
      strategy?: null
    ): ReserveInterestRateStrategyChangedEventFilter;
    ReserveInterestRateStrategyChanged(
      asset?: PromiseOrValue<string> | null,
      strategy?: null
    ): ReserveInterestRateStrategyChangedEventFilter;

    "ReserveUnfrozen(address)"(
      asset?: PromiseOrValue<string> | null
    ): ReserveUnfrozenEventFilter;
    ReserveUnfrozen(
      asset?: PromiseOrValue<string> | null
    ): ReserveUnfrozenEventFilter;

    "StableDebtTokenUpgraded(address,address,address)"(
      asset?: PromiseOrValue<string> | null,
      proxy?: PromiseOrValue<string> | null,
      implementation?: PromiseOrValue<string> | null
    ): StableDebtTokenUpgradedEventFilter;
    StableDebtTokenUpgraded(
      asset?: PromiseOrValue<string> | null,
      proxy?: PromiseOrValue<string> | null,
      implementation?: PromiseOrValue<string> | null
    ): StableDebtTokenUpgradedEventFilter;

    "StableRateDisabledOnReserve(address)"(
      asset?: PromiseOrValue<string> | null
    ): StableRateDisabledOnReserveEventFilter;
    StableRateDisabledOnReserve(
      asset?: PromiseOrValue<string> | null
    ): StableRateDisabledOnReserveEventFilter;

    "StableRateEnabledOnReserve(address)"(
      asset?: PromiseOrValue<string> | null
    ): StableRateEnabledOnReserveEventFilter;
    StableRateEnabledOnReserve(
      asset?: PromiseOrValue<string> | null
    ): StableRateEnabledOnReserveEventFilter;

    "VariableDebtTokenUpgraded(address,address,address)"(
      asset?: PromiseOrValue<string> | null,
      proxy?: PromiseOrValue<string> | null,
      implementation?: PromiseOrValue<string> | null
    ): VariableDebtTokenUpgradedEventFilter;
    VariableDebtTokenUpgraded(
      asset?: PromiseOrValue<string> | null,
      proxy?: PromiseOrValue<string> | null,
      implementation?: PromiseOrValue<string> | null
    ): VariableDebtTokenUpgradedEventFilter;
  };

  estimateGas: {
    activateReserve(
      asset: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    configureReserveAsCollateral(
      asset: PromiseOrValue<string>,
      ltv: PromiseOrValue<BigNumberish>,
      liquidationThreshold: PromiseOrValue<BigNumberish>,
      liquidationBonus: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    deactivateReserve(
      asset: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    disableBorrowingOnReserve(
      asset: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    disableReserveStableRate(
      asset: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    enableBorrowingOnReserve(
      asset: PromiseOrValue<string>,
      stableBorrowRateEnabled: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    enableReserveStableRate(
      asset: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    freezeReserve(
      asset: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    initReserve(
      aTokenImpl: PromiseOrValue<string>,
      stableDebtTokenImpl: PromiseOrValue<string>,
      variableDebtTokenImpl: PromiseOrValue<string>,
      underlyingAssetDecimals: PromiseOrValue<BigNumberish>,
      interestRateStrategyAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    initialize(
      provider: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setPoolPause(
      val: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setReserveFactor(
      asset: PromiseOrValue<string>,
      reserveFactor: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setReserveInterestRateStrategyAddress(
      asset: PromiseOrValue<string>,
      rateStrategyAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unfreezeReserve(
      asset: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateAToken(
      asset: PromiseOrValue<string>,
      implementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateStableDebtToken(
      asset: PromiseOrValue<string>,
      implementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateVariableDebtToken(
      asset: PromiseOrValue<string>,
      implementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    activateReserve(
      asset: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    configureReserveAsCollateral(
      asset: PromiseOrValue<string>,
      ltv: PromiseOrValue<BigNumberish>,
      liquidationThreshold: PromiseOrValue<BigNumberish>,
      liquidationBonus: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    deactivateReserve(
      asset: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    disableBorrowingOnReserve(
      asset: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    disableReserveStableRate(
      asset: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    enableBorrowingOnReserve(
      asset: PromiseOrValue<string>,
      stableBorrowRateEnabled: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    enableReserveStableRate(
      asset: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    freezeReserve(
      asset: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    initReserve(
      aTokenImpl: PromiseOrValue<string>,
      stableDebtTokenImpl: PromiseOrValue<string>,
      variableDebtTokenImpl: PromiseOrValue<string>,
      underlyingAssetDecimals: PromiseOrValue<BigNumberish>,
      interestRateStrategyAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    initialize(
      provider: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setPoolPause(
      val: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setReserveFactor(
      asset: PromiseOrValue<string>,
      reserveFactor: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setReserveInterestRateStrategyAddress(
      asset: PromiseOrValue<string>,
      rateStrategyAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unfreezeReserve(
      asset: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateAToken(
      asset: PromiseOrValue<string>,
      implementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateStableDebtToken(
      asset: PromiseOrValue<string>,
      implementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateVariableDebtToken(
      asset: PromiseOrValue<string>,
      implementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
