/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as aaveV2 from "./aave-v2";
import type * as compound from "./compound";

export type { aaveV2 };

export type { compound };
export type { ERC20 } from "./ERC20";
export * as factories from "./factories";
export type { MorphoAaveV2 } from "./aave-v2/mainnet/MorphoAaveV2";
export { MorphoAaveV2__factory } from "./factories/aave-v2/mainnet/MorphoAaveV2__factory";
export type { MorphoAaveV2Lens } from "./aave-v2/mainnet/MorphoAaveV2Lens";
export { MorphoAaveV2Lens__factory } from "./factories/aave-v2/mainnet/MorphoAaveV2Lens__factory";
export type { MorphoCompound } from "./compound/MorphoCompound";
export { MorphoCompound__factory } from "./factories/compound/MorphoCompound__factory";
export type { MorphoCompoundLens } from "./compound/MorphoCompoundLens";
export { MorphoCompoundLens__factory } from "./factories/compound/MorphoCompoundLens__factory";
export { ERC20__factory } from "./factories/ERC20__factory";

export { default as addresses } from "./addresses";
